### ISSUE TITLE
Criar testes pra tela de categoria

### ISSUE THREAD

**Issue by alessandrofeitoza** [iwtrainingbr/carrinho-virtual-app#36]
## User Story
- [x] Acessar a página principal 
- [x] Abre o menu lateral
- [x] Ver a opção "Categorias"
- [x] Clica na opção "Categorias"
- [x] Garante que está na tela de Categorias
- [x] O menu deve estar fechado
- [x] O usuário deverá conseguir ver a palavra " - Categorias -"
- [x] O usuário consegue ver ao menos 1 categoria

**Comment by ceciliaamora** [comment]
Resolve #36
